spring:
  thymeleaf:
  prefix: classpath:/templates/
  devtools:
    restart:
      enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cdb-2xyi7ci0.bj.tencentcdb.com:10097/blog2?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    hikari: # springboot 2.0 整合了hikari ,据说这是目前性能最好的java数据库连接池
      username: root
      password: xiayizhen123
  jpa:
    hibernate:
      ddl-auto: update  # 第一次建表create  后面用update，要不然每次重启都会新建表
    show-sql: true


